6.3
art3miy/spbu pull request #25
Opened 2018-11-09 10:58 UTC by art3miy

2018-11-20 10:02 UTC, jzuken requested changes

2018-11-20 10:02 UTC, jzuken commented on sem1/hw6/6.3.cpp
> +int main()
память почистить ещё

2018-11-24 18:48 UTC, jzuken commented
input the power of your polynom
2
input the coefs of your polynom
0
0
1

0x+ 1


ну такое

2018-11-24 20:19 UTC, art3miy commented
Ну просто это многочлен не второй степени, если коэффициент при x^2 равен нулю, или так не пойдет?

2018-12-04 14:21 UTC, merged